update pcre to 8.33

diff --git a/pcre/RunTest b/pcre/RunTest
--- a/pcre/RunTest
+++ b/pcre/RunTest
@@ -1,8 +1,9 @@
 #! /bin/sh
 
+###############################################################################
 # Run the PCRE tests using the pcretest program. The appropriate tests are
 # selected, depending on which build-time options were used.
-
+#
 # All tests are now run both with and without -s, to ensure that everything is
 # tested with and without studying. However, there are some tests that produce
 # different output after studying, typically when we are tracing the actual
@@ -12,23 +13,39 @@
 # any difference to their output. There is also one test which compiles invalid
 # UTF-8 with the UTF-8 check turned off; for this, studying must also be
 # disabled with /SS.
-
+#
 # When JIT support is available, all the tests are also run with -s+ to test
-# (again, almost) everything with studying and the JIT option. There are also
-# two tests for JIT-specific features, one to be run when JIT support is
-# available, and one when it is not.
+# (again, almost) everything with studying and the JIT option, unless "nojit"
+# is given on the command line. There are also two tests for JIT-specific
+# features, one to be run when JIT support is available (unless "nojit" is
+# specified), and one when it is not.
+#
+# Whichever of the 8-, 16- and 32-bit libraries exist are tested. It is also
+# possible to select which to test by giving "-8", "-16" or "-32" on the
+# command line.
+#
+# As well as "nojit", "-8", "-16", and "-32", arguments for this script are
+# individual test numbers, ranges of tests such as 3-6 or 3- (meaning 3 to the
+# end), or a number preceded by ~ to exclude a test. For example, "3-15 ~10"
+# runs tests 3 to 15, excluding test 10, and just "~10" runs all the tests
+# except test 10. Whatever order the arguments are in, the tests are always run
+# in numerical order.
 
-# Whichever of the 8-bit and 16-bit libraries exist are tested. It is also
-# possible to select which to test by the arguments -8 or -16.
-
-# Other arguments for this script can be individual test numbers, or the word
-# "valgrind", or "sim" followed by an argument to run cross-compiled
-# executables under a simulator, for example:
+# Other arguments can be one of the words "valgrind", "valgrind-log", or "sim"
+# followed by an argument to run cross- compiled executables under a simulator,
+# for example:
 #
 # RunTest 3 sim "qemu-arm -s 8388608"
 #
-# Finally, if the script is obeyed as "RunTest list", a list of available
-# tests is output, but none of them are run.
+# There are two special cases where only one argument is allowed:
+#
+# If the first and only argument is "ebcdic", the script runs the special
+# EBCDIC test that can be useful for checking certain EBCDIC features, even
+# when run in an ASCII environment.
+#
+# If the script is obeyed as "RunTest list", a list of available tests is
+# output, but none of them are run.
+###############################################################################
 
 # Define test titles in variables so that they can be output as a list. Some
 # of them are modified (e.g. with -8 or -16) when used in the actual tests.
@@ -50,12 +67,18 @@ title13="Test 13: JIT-specific features (JIT not available)"
 title14="Test 14: Specials for the basic 8-bit library"
 title15="Test 15: Specials for the 8-bit library with UTF-8 support"
 title16="Test 16: Specials for the 8-bit library with Unicode propery support"
-title17="Test 17: Specials for the basic 16-bit library"
-title18="Test 18: Specials for the 16-bit library with UTF-16 support"
-title19="Test 19: Specials for the 16-bit library with Unicode propery support"
-title20="Test 20: DFA specials for the basic 16-bit library"
-title21="Test 21: Reloads for the basic 16-bit library"
-title22="Test 22: Reloads for the 16-bit library with UTF-16 support"
+title17="Test 17: Specials for the basic 16/32-bit library"
+title18="Test 18: Specials for the 16/32-bit library with UTF-16/32 support"
+title19="Test 19: Specials for the 16/32-bit library with Unicode property support"
+title20="Test 20: DFA specials for the basic 16/32-bit library"
+title21="Test 21: Reloads for the basic 16/32-bit library"
+title22="Test 22: Reloads for the 16/32-bit library with UTF-16/32 support"
+title23="Test 23: Specials for the 16-bit library"
+title24="Test 24: Specials for the 16-bit library with UTF-16 support"
+title25="Test 25: Specials for the 32-bit library"
+title26="Test 26: Specials for the 32-bit library with UTF-32 support"
+
+maxtest=26
 
 if [ $# -eq 1 -a "$1" = "list" ]; then
   echo $title1
@@ -80,21 +103,78 @@ if [ $# -eq 1 -a "$1" = "list" ]; then
   echo $title20
   echo $title21
   echo $title22
+  echo $title23
+  echo $title24
+  echo $title25
+  echo $title26
   exit 0
 fi
 
+# Set up a suitable "diff" command for comparison. Some systems
+# have a diff that lacks a -u option. Try to deal with this.
+
+cf="diff"
+diff -u /dev/null /dev/null 2>/dev/null && cf="diff -u"
+
+# Find the test data
+
+if [ -n "$srcdir" -a -d "$srcdir" ] ; then
+  testdata="$srcdir/testdata"
+elif [ -d "./testdata" ] ; then
+  testdata=./testdata
+elif [ -d "../testdata" ] ; then
+  testdata=../testdata
+else
+  echo "Cannot find the testdata directory"
+  exit 1
+fi
+
+
+# ------ Special EBCDIC Test -------
+
+if [ $# -eq 1 -a "$1" = "ebcdic" ]; then
+  ./pcretest -C ebcdic >/dev/null
+  ebcdic=$?
+  if [ $ebcdic -ne 1 ] ; then
+    echo "Cannot run EBCDIC tests: EBCDIC support not compiled"
+    exit 1
+  fi
+
+  for opt in "" "-s" "-dfa" "-s -dfa"; do
+    ./pcretest -q $opt $testdata/testinputEBC >testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutputEBC testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "  OK with study"
+    elif [ "$opt" = "-dfa" ] ; then echo "  OK using DFA"
+    elif [ "$opt" = "-s -dfa" ] ; then echo "  OK using DFA with study"
+    else echo "  OK"
+    fi
+  done
+
+exit 0
+fi
+
+
+# ------ Normal Tests ------
+
 # Default values
 
-valgrind=
-sim=
 arg8=
 arg16=
+arg32=
+nojit=
+sim=
+skip=
+valgrind=
 
 # This is in case the caller has set aliases (as I do - PH)
 unset cp ls mv rm
 
-# Select which tests to run; for those that are explicitly requested, check
-# that the necessary optional facilities are available.
+# Process options and select which tests to run; for those that are explicitly
+# requested, check that the necessary optional facilities are available.
 
 do1=no
 do2=no
@@ -118,6 +198,10 @@ do19=no
 do20=no
 do21=no
 do22=no
+do23=no
+do24=no
+do25=no
+do26=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -143,37 +227,46 @@ while [ $# -gt 0 ] ; do
    20) do20=yes;;
    21) do21=yes;;
    22) do22=yes;;
+   23) do23=yes;;
+   24) do24=yes;;
+   25) do25=yes;;
+   26) do26=yes;;
    -8) arg8=yes;;
   -16) arg16=yes;;
-   valgrind) valgrind="valgrind -q --smc-check=all";;
+  -32) arg32=yes;;
+   nojit) nojit=yes;;
    sim) shift; sim=$1;;
-    *) echo "Unknown test number '$1'"; exit 1;;
+   valgrind) valgrind="valgrind --tool=memcheck -q --smc-check=all";;
+   valgrind-log) valgrind="valgrind --tool=memcheck --num-callers=30 --leak-check=no --error-limit=no --smc-check=all --log-file=report.%p ";;
+   ~*)
+     if expr "$1" : '~[0-9][0-9]*$' >/dev/null; then
+       skip="$skip `expr "$1" : '~\([0-9]*\)*$'`"
+     else
+       echo "Unknown option or test selector '$1'"; exit 1
+     fi
+   ;;
+   *-*)
+     if expr "$1" : '[0-9][0-9]*-[0-9]*$' >/dev/null; then
+       tf=`expr "$1" : '\([0-9]*\)'`
+       tt=`expr "$1" : '.*-\([0-9]*\)'`
+       if [ "$tt" = "" ] ; then tt=$maxtest; fi
+       if expr \( "$tf" "<" 1 \) \| \( "$tt" ">" "$maxtest" \) >/dev/null; then
+         echo "Invalid test range '$1'"; exit 1
+       fi
+       while expr "$tf" "<=" "$tt" >/dev/null; do
+         eval do${tf}=yes
+         tf=`expr $tf + 1`
+       done
+     else
+       echo "Invalid test range '$1'"; exit 1
+     fi
+   ;;
+   *) echo "Unknown option or test selector '$1'"; exit 1;;
   esac
   shift
 done
 
-# Set up a suitable "diff" command for comparison. Some systems
-# have a diff that lacks a -u option. Try to deal with this.
-
-if diff -u /dev/null /dev/null; then cf="diff -u"; else cf="diff"; fi
-
-# Find the test data
-
-if [ -n "$srcdir" -a -d "$srcdir" ] ; then
-  testdata="$srcdir/testdata"
-elif [ -d "./testdata" ] ; then
-  testdata=./testdata
-elif [ -d "../testdata" ] ; then
-  testdata=../testdata
-else
-  echo "Cannot find the testdata directory"
-  exit 1
-fi
-
-# Find which optional facilities are available. In some Windows environments
-# the output of pcretest -C has CRLF at the end of each line, but the shell
-# strips only linefeeds from the output of a `backquoted` command. Hence the
-# alternative patterns.
+# Find which optional facilities are available.
 
 $sim ./pcretest -C linksize >/dev/null
 link_size=$?
@@ -186,41 +279,62 @@ if [ $link_size -gt 4 ] ; then
   exit 1
 fi
 
-# Both 8-bit and 16-bit character strings may be supported, but only one
-# need be.
+# All of 8-bit, 16-bit, and 32-bit character strings may be supported, but only
+# one need be.
 
 $sim ./pcretest -C pcre8 >/dev/null
 support8=$?
 $sim ./pcretest -C pcre16 >/dev/null
 support16=$?
-if [ `expr $support8 + $support16` -eq 2 ] ; then
-  test8=
-  test16=-16
-  if [ "$arg8" = yes -a "$arg16" != yes ] ; then
-    test16=skip
-  fi
-  if [ "$arg16" = yes -a "$arg8" != yes ] ; then
-    test8=skip
-  fi
-else
+$sim ./pcretest -C pcre32 >/dev/null
+support32=$?
+
+# Initialize all bitsizes skipped
+
+test8=skip
+test16=skip
+test32=skip
+
+# If no bitsize arguments, select all that are available
+
+if [ "$arg8$arg16$arg32" = "" ] ; then
   if [ $support8 -ne 0 ] ; then
-    if [ "$arg16" = yes ] ; then
-      echo "Cannot run 16-bit library tests: 16-bit library not compiled"
-      exit 1
-    fi
     test8=
-    test16=skip
-  else
-    if [ "$arg8" = yes ] ; then
+  fi
+  if [ $support16 -ne 0 ] ; then
+    test16=-16
+  fi
+  if [ $support32 -ne 0 ] ; then
+    test32=-32
+  fi
+
+# Select requested bit sizes
+
+else
+  if [ "$arg8" = yes ] ; then
+    if [ $support8 -eq 0 ] ; then
       echo "Cannot run 8-bit library tests: 8-bit library not compiled"
       exit 1
     fi
-    test8=skip
+    test8=
+  fi
+  if [ "$arg16" = yes ] ; then
+    if [ $support16 -eq 0 ] ; then
+      echo "Cannot run 16-bit library tests: 16-bit library not compiled"
+      exit 1
+    fi
     test16=-16
+  fi
+  if [ "$arg32" = yes ] ; then
+    if [ $support32 -eq 0 ] ; then
+      echo "Cannot run 32-bit library tests: 32-bit library not compiled"
+      exit 1
+    fi
+    test32=-32
   fi
 fi
 
-# UTF support always applies to both bit sizes if both are supported; we can't
+# UTF support always applies to all bit sizes if both are supported; we can't
 # have UTF-8 support without UTF-16 support (for example).
 
 $sim ./pcretest -C utf >/dev/null
@@ -232,9 +346,15 @@ ucp=$?
 jitopt=
 $sim ./pcretest -C jit >/dev/null
 jit=$?
-if [ $jit -ne 0 ] ; then
+if [ $jit -ne 0 -a "$nojit" != "yes" ] ; then
   jitopt=-s+
 fi
+
+# Handle any explicit skips
+
+for i in $skip; do eval do$i=no; done
+
+# If any unsuitable tests were explicitly requested, grumble.
 
 if [ $utf -eq 0 ] ; then
   if [ $do4 = yes ] ; then
@@ -304,14 +424,15 @@ else
 fi
 
 # If no specific tests were requested, select all. Those that are not
-# relevant will be skipped.
+# relevant will be automatically skipped.
 
 if [ $do1  = no -a $do2  = no -a $do3  = no -a $do4  = no -a \
      $do5  = no -a $do6  = no -a $do7  = no -a $do8  = no -a \
      $do9  = no -a $do10 = no -a $do11 = no -a $do12 = no -a \
      $do13 = no -a $do14 = no -a $do15 = no -a $do16 = no -a \
      $do17 = no -a $do18 = no -a $do19 = no -a $do20 = no -a \
-     $do21 = no -a $do22 = no ] ; then
+     $do21 = no -a $do22 = no -a $do23 = no -a $do24 = no -a \
+     $do25 = no -a $do26 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
@@ -334,7 +455,16 @@ if [ $do1  = no -a $do2  = no -a $do3  = no -a $do4  = no -a \
   do20=yes
   do21=yes
   do22=yes
+  do23=yes
+  do24=yes
+  do25=yes
+  do26=yes
 fi
+
+# Handle any explicit skips (again, so that an argument list may consist only
+# of explicit skips).
+
+for i in $skip; do eval do$i=no; done
 
 # Show which release and which test data
 
@@ -342,11 +472,13 @@ echo ""
 echo PCRE C library tests using test data from $testdata
 $sim ./pcretest /dev/null
 
-for bmode in "$test8" "$test16"; do
+for bmode in "$test8" "$test16" "$test32"; do
   case "$bmode" in
     skip) continue;;
-    -16)  if [ "$test8" != "skip" ] ; then echo ""; fi
+    -16)  if [ "$test8$test32" != "skipskip" ] ; then echo ""; fi
           bits=16; echo "---- Testing 16-bit library ----"; echo "";;
+    -32)  if [ "$test8$test16" != "skipskip" ] ; then echo ""; fi
+          bits=32; echo "---- Testing 32-bit library ----"; echo "";;
     *)    bits=8; echo "---- Testing 8-bit library ----"; echo "";;
   esac
 
@@ -616,7 +748,7 @@ fi
 
 if [ $do12 = yes ] ; then
   echo $title12
-  if [ $jit -eq 0 ] ; then
+  if [ $jit -eq 0 -o "$nojit" = "yes" ] ; then
     echo "  Skipped because JIT is not available or not usable"
   else
     $sim $valgrind ./pcretest -q $bmode $testdata/testinput12 testtry
@@ -650,10 +782,11 @@ fi
 
 if [ "$do14" = yes ] ; then
   echo $title14
-  if [ "$bits" = "16" ] ; then
-    echo "  Skipped when running 16-bit tests"
+  if [ "$bits" = "16" -o "$bits" = "32" ] ; then
+    echo "  Skipped when running 16/32-bit tests"
   else
     cp -f $testdata/saved16 testsaved16
+    cp -f $testdata/saved32 testsaved32
     for opt in "" "-s" $jitopt; do
       $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput14 testtry
       if [ $? = 0 ] ; then
@@ -673,8 +806,8 @@ fi
 
 if [ "$do15" = yes ] ; then
   echo $title15
-  if [ "$bits" = "16" ] ; then
-    echo "  Skipped when running 16-bit tests"
+  if [ "$bits" = "16" -o "$bits" = "32" ] ; then
+    echo "  Skipped when running 16/32-bit tests"
   elif [ $utf -eq 0 ] ; then
     echo "  Skipped because UTF-$bits support is not available"
   else
@@ -697,8 +830,8 @@ fi
 
 if [ $do16 = yes ] ; then
   echo $title16
-  if [ "$bits" = "16" ] ; then
-    echo "  Skipped when running 16-bit tests"
+  if [ "$bits" = "16" -o "$bits" = "32" ] ; then
+    echo "  Skipped when running 16/32-bit tests"
   elif [ $ucp -eq 0 ] ; then
     echo "  Skipped because Unicode property support is not available"
   else
@@ -717,7 +850,7 @@ if [ $do16 = yes ] ; then
   fi
 fi
 
-# Tests for 16-bit-specific features
+# Tests for 16/32-bit-specific features
 
 if [ $do17 = yes ] ; then
   echo $title17
@@ -739,7 +872,7 @@ if [ $do17 = yes ] ; then
   fi
 fi
 
-# Tests for 16-bit-specific features (UTF-16 support)
+# Tests for 16/32-bit-specific features (UTF-16/32 support)
 
 if [ $do18 = yes ] ; then
   echo $title18
@@ -751,7 +884,7 @@ if [ $do18 = yes ] ; then
     for opt in "" "-s" $jitopt; do
       $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput18 testtry
       if [ $? = 0 ] ; then
-        $cf $testdata/testoutput18 testtry
+        $cf $testdata/testoutput18-$bits testtry
         if [ $? != 0 ] ; then exit 1; fi
       else exit 1
       fi
@@ -763,7 +896,7 @@ if [ $do18 = yes ] ; then
   fi
 fi
 
-# Tests for 16-bit-specific features (Unicode property support)
+# Tests for 16/32-bit-specific features (Unicode property support)
 
 if [ $do19 = yes ] ; then
   echo $title19
@@ -787,7 +920,7 @@ if [ $do19 = yes ] ; then
   fi
 fi
 
-# Tests for 16-bit-specific features in DFA non-UTF-16 mode
+# Tests for 16/32-bit-specific features in DFA non-UTF-16/32 mode
 
 if [ $do20 = yes ] ; then
   echo $title20
@@ -795,7 +928,7 @@ if [ $do20 = yes ] ; then
     echo "  Skipped when running 8-bit tests"
   else
     for opt in "" "-s"; do
-      $sim $valgrind ./pcretest -q $bmode $opt $testdata/testinput20 testtry
+      $sim $valgrind ./pcretest -q $bmode $opt -dfa $testdata/testinput20 testtry
       if [ $? = 0 ] ; then
         $cf $testdata/testoutput20 testtry
         if [ $? != 0 ] ; then exit 1; fi
@@ -808,7 +941,7 @@ if [ $do20 = yes ] ; then
   fi
 fi
 
-# Tests for reloads with 16-bit library
+# Tests for reloads with 16/32-bit library
 
 if [ $do21 = yes ] ; then
   echo $title21
@@ -820,9 +953,11 @@ if [ $do21 = yes ] ; then
     cp -f $testdata/saved8 testsaved8
     cp -f $testdata/saved16LE-1 testsaved16LE-1
     cp -f $testdata/saved16BE-1 testsaved16BE-1
+    cp -f $testdata/saved32LE-1 testsaved32LE-1
+    cp -f $testdata/saved32BE-1 testsaved32BE-1
     $sim $valgrind ./pcretest -q $bmode $testdata/testinput21 testtry
     if [ $? = 0 ] ; then
-      $cf $testdata/testoutput21 testtry
+      $cf $testdata/testoutput21-$bits testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
@@ -830,7 +965,7 @@ if [ $do21 = yes ] ; then
   fi
 fi
 
-# Tests for reloads with 16-bit library (UTF-16 support)
+# Tests for reloads with 16/32-bit library (UTF-16 support)
 
 if [ $do22 = yes ] ; then
   echo $title22
@@ -843,9 +978,11 @@ if [ $do22 = yes ] ; then
   else
     cp -f $testdata/saved16LE-2 testsaved16LE-2
     cp -f $testdata/saved16BE-2 testsaved16BE-2
+    cp -f $testdata/saved32LE-2 testsaved32LE-2
+    cp -f $testdata/saved32BE-2 testsaved32BE-2
     $sim $valgrind ./pcretest -q $bmode $testdata/testinput22 testtry
     if [ $? = 0 ] ; then
-      $cf $testdata/testoutput22 testtry
+      $cf $testdata/testoutput22-$bits testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
@@ -853,7 +990,71 @@ if [ $do22 = yes ] ; then
   fi
 fi
 
-# End of loop for 8-bit/16-bit tests
+if [ $do23 = yes ] ; then
+  echo $title23
+  if [ "$bits" = "8" -o "$bits" = "32" ] ; then
+    echo "  Skipped when running 8/32-bit tests"
+  else
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput23 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput23 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    echo "  OK"
+  fi
+fi
+
+if [ $do24 = yes ] ; then
+  echo $title24
+  if [ "$bits" = "8" -o "$bits" = "32" ] ; then
+    echo "  Skipped when running 8/32-bit tests"
+  elif [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF-$bits support is not available"
+  else
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput24 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput24 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    echo "  OK"
+  fi
+fi
+
+if [ $do25 = yes ] ; then
+  echo $title25
+  if [ "$bits" = "8" -o "$bits" = "16" ] ; then
+    echo "  Skipped when running 8/16-bit tests"
+  else
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput25 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput25 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    echo "  OK"
+  fi
+fi
+
+if [ $do26 = yes ] ; then
+  echo $title26
+  if [ "$bits" = "8" -o "$bits" = "16" ] ; then
+    echo "  Skipped when running 8/16-bit tests"
+  elif [ $utf -eq 0 ] ; then
+    echo "  Skipped because UTF-$bits support is not available"
+  else
+    $sim $valgrind ./pcretest -q $bmode $testdata/testinput26 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput26 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    echo "  OK"
+  fi
+fi
+
+# End of loop for 8/16/32-bit tests
 done
 
 # Clean up local working files
